### PR TITLE
Mmap trace

### PR DESCRIPTION
**Pull request by ducorduck**
to solve #28

### CODE REVIEW

**Comment by lks9** [comment]
Sorry for taking so long. I think this is fine although not very readible in the end. I suggest:

* Use `page_count` instead of `offset` (you are counting the pages) and `seek_in_page` instead of `start_byte`. Same goes for the `_tail` versions (would be `tail_seek_in_page`).
* Don't use a tuple anywhere (you currently have one for `start_byte`). This gets just more confusing.

**Comment by lks9** [comment]
Sorry, I am currently working on the new trace format for #53 and need to touch this file. Can you do the above improvements (if you are not ok, you can also use other names as long as it gets less confusing then the current state)? Otherwise, I will do it myself. Thanks!

**Comment by ducorduck** [comment]
Sure. I'm working on it!

**Comment by ducorduck** [comment]
would this works?

**Comment by lks9** [comment]
Sorry, was still not good. I realized that 'offset' was actually the correct name. But you still had 'start_byte' and also some 'bufferRange' at some point which made no sense at all (because it wasn't a range, it was just a position). I renamed it myself now.

I also tried it out with your bigtrace. It seems fine, so I think this one should be ready to merge.

**Comment by lks9** [comment]
I am closing this as no longer mergeable. It would still be nice if this could be implemented...

**Pull request closed without merging**
